name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: Ethan-Xingyue
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_padding: 0, 8 + 6%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no
          plugin_achievements_display: compact

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: Ethan-Xingyue
          base: ""
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
